In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
student_analysis = 'Copy of Newer Analysis - Student Summary.csv'
stud_summary = pd.read_csv(student_analysis)

In [3]:
pd.options.display.max_columns = 1000
stud_summary.sort_values(by=['Total no. of sessions']);

In [4]:
stud_summary = stud_summary[stud_summary['Result'] != 'Exempt']

In [5]:
stud_summary.sort_values(by=['Channel ID'], ascending = True, inplace = True)

In [6]:
stud_summary = stud_summary.reset_index(drop=True);

In [7]:
stud_summary.head()

,Student Number,Telegram ID,First Name,Last Name,GEMP,Mobile number,Email,Result,Channel ID,Total no. of sessions,Avg chunks per session,Current chunk,Remaining sessions,< 330 avg chunks per session,End chunk at current rate,Sessions to reach 330,Sessions to reach 378,Sessions to reach 487,Sessions to reach 560,Sessions to reach 650,Total no. of sessions.1,Deficit,0.767,0.6614,1
0,1056196,503630339.0,Mmaenetjie,Sefiti,2.0,818038901.0,1056196@students.wits.ac.za,M1,-319743207.0,51.0,6.30,382,45.0,6.8,M3 Complete,Reached 330,9.20,24.24,16.23,20.01,69.68,24.68,NaN,NaN,NaN
1,1080309,453872843.0,Makgotso,Mogafe,1.0,742278497.0,1080309@students.wits.ac.za,M2,-319717963.0,6.0,10.40,449,90.0,NaN,M3 Complete,NaN,NaN,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN
2,1443976,531904227.0,Sandile,Matukane,1.0,798049316.0,1443976@students.wits.ac.za,M1,-319652574.0,2.0,3.50,384,94.0,1.0,M3 Complete,Reached 330,62.58,164.80,110.37,136.07,473.83,379.83,NaN,NaN,NaN
3,671148,460952442.0,Joel,Pabu,2.0,745597572.0,671148@students.wits.ac.za,M1,-318942677.0,13.0,8.17,116,83.0,7.5,M3 Complete,28.53,8.34,21.97,14.72,18.14,91.71,8.71,NaN,NaN,NaN
4,837717,484863743.0,Kyle,Kretzmer,2.0,823081222.0,837717@students.wits.ac.za,M1,-318907942.0,49.0,8.32,450,47.0,9.7,M3 Complete,Reached 330,6.45,16.99,11.38,14.03,48.85,1.85,NaN,NaN,NaN

In [8]:
progress_log = pd.read_csv('Copy of Progress Log - Progress List.csv')

In [9]:
progress_log.head()

   Channel ID   Student ID         Student name  Chunk Number
0  -278666511  276042080.0       Uthini Support           535
1  -263310644  493235383.0      Rosanne Bentley           535
2  -267458810  422698657.0     Sabrina Stransky           529
3  -264244622  510004183.0  Daniel Von Hoesslin           524
4  -250905986  501784167.0    Welheminah Marumo           522

In [10]:
progress_log.sort_values(by=['Channel ID'], ascending = True, inplace = True)
progress_log = progress_log.reset_index(drop=True);

In [11]:
progress_log["Progress Percentage"] = (progress_log['Chunk Number']/650 *100).round(2)

In [12]:
stud_summary.rename(columns={'Total no. of sessions':'Sessions completed'}, inplace=True);
stud_summary.rename(columns={'Remaining sessions':'Sessions remaining'}, inplace=True);

In [13]:
stud_full = pd.merge(stud_summary, progress_log[['Channel ID','Progress Percentage']], on=['Channel ID'])

In [14]:
stud_full.head()

,Student Number,Telegram ID,First Name,Last Name,GEMP,Mobile number,Email,Result,Channel ID,Sessions completed,Avg chunks per session,Current chunk,Sessions remaining,< 330 avg chunks per session,End chunk at current rate,Sessions to reach 330,Sessions to reach 378,Sessions to reach 487,Sessions to reach 560,Sessions to reach 650,Total no. of sessions.1,Deficit,0.767,0.6614,1,Progress Percentage
0,1056196,503630339.0,Mmaenetjie,Sefiti,2.0,818038901.0,1056196@students.wits.ac.za,M1,-319743207.0,51.0,6.30,382,45.0,6.8,M3 Complete,Reached 330,9.20,24.24,16.23,20.01,69.68,24.68,NaN,NaN,NaN,60.77
1,1080309,453872843.0,Makgotso,Mogafe,1.0,742278497.0,1080309@students.wits.ac.za,M2,-319717963.0,6.0,10.40,449,90.0,NaN,M3 Complete,NaN,NaN,NaN,0.00,0.00,NaN,NaN,NaN,NaN,NaN,69.08
2,1443976,531904227.0,Sandile,Matukane,1.0,798049316.0,1443976@students.wits.ac.za,M1,-319652574.0,2.0,3.50,384,94.0,1.0,M3 Complete,Reached 330,62.58,164.80,110.37,136.07,473.83,379.83,NaN,NaN,NaN,59.08
3,671148,460952442.0,Joel,Pabu,2.0,745597572.0,671148@students.wits.ac.za,M1,-318942677.0,13.0,8.17,116,83.0,7.5,M3 Complete,28.53,8.34,21.97,14.72,18.14,91.71,8.71,NaN,NaN,NaN,21.23
4,837717,484863743.0,Kyle,Kretzmer,2.0,823081222.0,837717@students.wits.ac.za,M1,-318907942.0,49.0,8.32,450,47.0,9.7,M3 Complete,Reached 330,6.45,16.99,11.38,14.03,48.85,1.85,NaN,NaN,NaN,71.08

In [15]:
stud_full.columns.get_loc('< 330 avg chunks per session')

13

In [16]:
stud_full.drop(stud_full.iloc[:, 13:25], axis=1, inplace=True)
stud_full.head()

,Student Number,Telegram ID,First Name,Last Name,GEMP,Mobile number,Email,Result,Channel ID,Sessions completed,Avg chunks per session,Current chunk,Sessions remaining,Progress Percentage
0,1056196,503630339.0,Mmaenetjie,Sefiti,2.0,818038901.0,1056196@students.wits.ac.za,M1,-319743207.0,51.0,6.30,382,45.0,60.77
1,1080309,453872843.0,Makgotso,Mogafe,1.0,742278497.0,1080309@students.wits.ac.za,M2,-319717963.0,6.0,10.40,449,90.0,69.08
2,1443976,531904227.0,Sandile,Matukane,1.0,798049316.0,1443976@students.wits.ac.za,M1,-319652574.0,2.0,3.50,384,94.0,59.08
3,671148,460952442.0,Joel,Pabu,2.0,745597572.0,671148@students.wits.ac.za,M1,-318942677.0,13.0,8.17,116,83.0,21.23
4,837717,484863743.0,Kyle,Kretzmer,2.0,823081222.0,837717@students.wits.ac.za,M1,-318907942.0,49.0,8.32,450,47.0,71.08

In [17]:
sessions = pd.read_csv('Student sessions as at 31 July 2018 (1) - Sessions.csv')

In [18]:
sessions.dtypes

Date                 object
Channel ID            int64
Start time           object
End time             object
Student ID           object
Student Name         object
Tutor ID            float64
Tutor Name           object
Start chunk           int64
End chunk             int64
Number of chunks      int64
Session duration     object
dtype: object

In [19]:
sessions['Start time'] = pd.to_datetime(sessions['Start time']).apply(lambda x: x.time())
sessions['End time'] = pd.to_datetime(sessions['End time']).apply(lambda x: x.time())

In [20]:
sessions['Date'] = pd.to_datetime(sessions['Date'])

In [21]:
sessions['Week_Number'] = sessions['Date'].dt.week

In [22]:
import random
sessions['Generated session ID'] = random.sample(range(1, 50000), 25250)

In [23]:
sessions.to_csv('Weekly sessions R.csv', index=False)

In [24]:
weekly_avg = pd.read_csv('Weekly sessions R - average sessions p week.csv')

In [25]:
weekly_avg.drop([0], inplace = True);

In [26]:
weekly_avg.rename(columns={'Unnamed: 0': 'Channel ID'}, inplace=True);

In [27]:
weekly_avg.rename(columns={'avg ': 'weekly avg'}, inplace=True)
weekly_avg.head()

    Channel ID  weekly avg
1 -319743207.0    2.909091
2 -319717963.0    1.285714
3 -319652574.0    1.000000
4 -318942677.0    2.363636
5 -318907942.0    2.818182

In [28]:
weeks = []
df = stud_full

for row in df['GEMP']: 
    if row ==1.0:
        weeks.append(11)
    elif row==2.0:
        weeks.append(9)
    else:
        weeks.append('error')
        
df['Weeks Remaining'] = weeks

In [29]:
df['Current chunk'] = df['Current chunk'].astype('int')

In [30]:
df['Chunks remaining']= 660 - df['Current chunk']

In [31]:
df = pd.merge(stud_full, weekly_avg, on=['Channel ID'])

In [32]:
df['weekly avg'] = df['weekly avg'].round(2)

In [33]:
df.head()

,Student Number,Telegram ID,First Name,Last Name,GEMP,Mobile number,Email,Result,Channel ID,Sessions completed,Avg chunks per session,Current chunk,Sessions remaining,Progress Percentage,Weeks Remaining,Chunks remaining,weekly avg
0,1056196,503630339.0,Mmaenetjie,Sefiti,2.0,818038901.0,1056196@students.wits.ac.za,M1,-319743207.0,51.0,6.30,382,45.0,60.77,9,278,2.91
1,1080309,453872843.0,Makgotso,Mogafe,1.0,742278497.0,1080309@students.wits.ac.za,M2,-319717963.0,6.0,10.40,449,90.0,69.08,11,211,1.29
2,1443976,531904227.0,Sandile,Matukane,1.0,798049316.0,1443976@students.wits.ac.za,M1,-319652574.0,2.0,3.50,384,94.0,59.08,11,276,1.00
3,671148,460952442.0,Joel,Pabu,2.0,745597572.0,671148@students.wits.ac.za,M1,-318942677.0,13.0,8.17,116,83.0,21.23,9,544,2.36
4,837717,484863743.0,Kyle,Kretzmer,2.0,823081222.0,837717@students.wits.ac.za,M1,-318907942.0,49.0,8.32,450,47.0,71.08,9,210,2.82

In [34]:
df['Projected sessions'] = df['weekly avg'] * df['Weeks Remaining']

In [35]:
df['Projected chunks'] = df['Avg chunks per session'] *df['Projected sessions']

In [36]:
df['Session deficit'] = df['Sessions remaining'] - df['Projected sessions']
df['Chunk deficit'] = df['Chunks remaining'] - df['Projected chunks']

In [37]:
df['Required chunks per week'] = df['Chunk deficit']/df['Weeks Remaining']

In [38]:
df['Required sessions at chunk rate']= df['Chunk deficit']/df['Avg chunks per session']

In [39]:
df['Required sessions per week']=df['Required sessions at chunk rate']/df['Weeks Remaining']

In [40]:
over_sessions = []
over_sessions = (df['Required sessions per week']* df['Weeks Remaining']) > df['Sessions remaining']
over_sessions.value_counts()

False    530
True      19
dtype: int64

In [41]:
df['Over session limit?'] = over_sessions

In [42]:
req1 = []

for row in df['Required sessions per week']: 
    if row <0:
        req1.append(0)
    else: 
        req1.append(row)
req1;
req1 = [round(x) for x in req1]

In [43]:
df['Required sessions per week'] = req1

In [44]:
df['Session rate'] = df['Required sessions per week'] - df['weekly avg'].astype(int)

In [45]:
req4 = []
for row in df['Session rate']: 
    if row > 0:
        req4.append(row)
    elif row < 0:
        req4.append('0')
    else:
        req4.append('0')
req4;

In [46]:
df['Session rate'] = req4

In [47]:
df.head()

,Student Number,Telegram ID,First Name,Last Name,GEMP,Mobile number,Email,Result,Channel ID,Sessions completed,Avg chunks per session,Current chunk,Sessions remaining,Progress Percentage,Weeks Remaining,Chunks remaining,weekly avg,Projected sessions,Projected chunks,Session deficit,Chunk deficit,Required chunks per week,Required sessions at chunk rate,Required sessions per week,Over session limit?,Session rate
0,1056196,503630339.0,Mmaenetjie,Sefiti,2.0,818038901.0,1056196@students.wits.ac.za,M1,-319743207.0,51.0,6.30,382,45.0,60.77,9,278,2.91,26.19,164.9970,18.81,113.0030,12.555889,17.936984,2,False,0
1,1080309,453872843.0,Makgotso,Mogafe,1.0,742278497.0,1080309@students.wits.ac.za,M2,-319717963.0,6.0,10.40,449,90.0,69.08,11,211,1.29,14.19,147.5760,75.81,63.4240,5.765818,6.098462,1,False,0
2,1443976,531904227.0,Sandile,Matukane,1.0,798049316.0,1443976@students.wits.ac.za,M1,-319652574.0,2.0,3.50,384,94.0,59.08,11,276,1.00,11.00,38.5000,83.00,237.5000,21.590909,67.857143,6,False,5
3,671148,460952442.0,Joel,Pabu,2.0,745597572.0,671148@students.wits.ac.za,M1,-318942677.0,13.0,8.17,116,83.0,21.23,9,544,2.36,21.24,173.5308,61.76,370.4692,41.163244,45.345067,5,False,3
4,837717,484863743.0,Kyle,Kretzmer,2.0,823081222.0,837717@students.wits.ac.za,M1,-318907942.0,49.0,8.32,450,47.0,71.08,9,210,2.82,25.38,211.1616,21.62,-1.1616,-0.129067,-0.139615,0,False,0

In [48]:
for_students = df[['Student Number', 'Last Name','First Name','Result','Progress Percentage',\
                  'weekly avg','Avg chunks per session','Session rate', 'Over session limit?']].copy()

In [49]:
for_students.to_csv('student report card R.csv', index=False)

In [50]:
#df['Session rate'] = df['Session rate'].astype(int)

In [51]:
# flag = []
# for row in df['Session rate']:
#     if row >= 3:
#         flag.append(1)
#     else:
#         flag.append(0)

In [52]:
# df['Session flag'] = flag